---
- hosts: all
  become: yes
  tasks:
  - name: Creating an empty file
    file:
      path: "touch.txt"
      state: touch

  - name: Creating a file with content
    copy:
      dest: "createdfile.txt"
      content: |
        file create by dalan 
        line 02