---
- hosts: all
  become: true
  tasks:
  - name: Creating an empty file
    file:
      path: "/home/Infosec/ansible/touch.txt"
      state: touch

  - name: Creating a file with content
    copy:
      dest: "/home/Infosec/ansible/createdfile.txt"
      content: |
        file create by dalan for testing
        