---
- hosts: all
  become: true
  tasks:
  - name: Creating an empty file
    file:
      path: "/temp/touch.txt"
      state: touch

  - name: Creating a file with content
    copy:
      dest: "/temp/createdfile.txt"
      content: |
        file create by dalan 
        line 02