
name: test function

on:
  workflow_call:
    inputs:
      GithubEnvironment:
        description: 'env'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true   
      DALAN_SECRET:
        required: true       

    

permissions:
  id-token: write
  contents: read

env:
  location: eastus
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './dalan_fun_new'
  AZURE_FUNCTIONAPP_NAME: 'dalanfuntest'
  PYTHON_VERSION: '3.9'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'commands'
      shell: bash
      run: |
        echo "__________________________________________________"
        echo ${{inputs.GithubEnvironment}}
