
name: test function

on:
  workflow_call:
    inputs:
      GithubEnvironment:
        description: 'env'
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true   
      AZURE_CLIENT_ID:
        required: true       

    

permissions:
  id-token: write
  contents: read

env:
  location: eastus
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './dalan_fun_new'
  AZURE_FUNCTIONAPP_NAME: 'dalanfuntest'
  PYTHON_VERSION: '3.9'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        echo "__________________________________________________"
        echo ${{inputs.GithubEnvironment}}
        echo ${{secrets.AZURE_CREDENTIALS}}
        echo ${{secrets.AZURE_CLIENT_ID}}
        #curl -X POST -H "Content-Type: application/json" -d "{\"name\": \"${{ inputs.name }}\", \"add\": \"${{ inputs.add }}\"}" https://testlab.azurewebsites.net/api/http_trigger1
        #az rest --method post --url 'https://testfundalan.azurewebsites.net/api/http_trigger1'
